DROP DATABASE IF EXISTS MYDB;
CREATE DATABASE MYDB;
USE MYDB;

CREATE TABLE LOAISANPHAM(
	MaLoaiSanPham INT AUTO_INCREMENT,
	TenLoaiSanPham VARCHAR(100),
	CONSTRAINT PK_LOAISANPHAM_MaLoai PRIMARY KEY(MaLoaiSanPham)
);

CREATE TABLE THUONGHIEU(
	 
);